version: '3'
services:
  app:
    container_name: app_php
    build:
      context: ./docker/app
      dockerfile: app.dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./src:/var/www/html

  nginx:
    container_name: app_nginx
    build:
      context: ./docker/web
      dockerfile: web.dockerfile
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/usr/share/nginx/html

volumes:
  app-data:

