version: '3'
services:
  db:
    container_name: BancoDados
    build:
      context: ./docker/db
      dockerfile: db.dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/db/db.sql:/docker-entrypoint-initdb.d/db.sql

  nginx:
    container_name: app_nginx
    build:
      context: ./docker/web
      dockerfile: web.dockerfile
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/usr/share/nginx/html
volumes:
  db-data:
