version: '3'
services:
  db:
    container_name: app_db
    build:
      context: .
      dockerfile: db.dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
volumes:
  db-data:
